# Generated by Django 4.2.3 on 2023-07-16 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tg_id', models.CharField(max_length=100)),
                ('tg_username', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_file', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.telegramuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.ticket')),
            ],
        ),
    ]
